### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by yuchiko** [OlejnikKristina/wood-landing-page#1]
1. Нулевку закрепить по высоте, там уезжает скролл вниз
1. `id="port"` не самое изящное сокращенние для portfolio, как и `cont`, зачем тут вообще было экономить?
1. иконки соц сетей хорошо бы в svg, или font-awesome
1. телефон и почту в `href:tel` и `href:mailto` соответственно
1. scroll ссылка с margin внутри очень странно сделана, там область ниже тоже кликабельна и это не совсем очевидно для пользователя.
1. 
> Если содержание имеет важное значение, но его позиция в потоке документа не важна, используйте figure
Ты думаешь, что те картинки важны по содержимому и их нужно группировать в этот тег?
1. Мне не нравятся твои волшебные 4% padding, не критично, но процентирование в отступах не всегда хорошо. width: 90%; подошло бы лучше, но это мое мнение
1. Я бы не привыкал использовать имена свойств в классах `flex`
1. Полоска у меня как-то заехала на меню и почему она отдельным элементом, если это очевидный `:after`
1. `meta` ставь до `link` в хеде

**Comment by OlejnikKristina** [comment]
1. Done.
2. Внутренний минималист пошаливал. "Краткость сестра таланта" думал он ...
3. уже в svg вместе со стрелкой
4. done
5. подправила, вроде норм
6. подправила.  нет, думаю не важны
7. любимые 4% padding я их уже во всех работах прописала ... В новых уже буду width-90% юзать (доверяю твоему мнению). А править уже сделанные чутка лень ))
8. тоже не буду к этому привыкать
9. действительно, полоска в  `:after` чувствует себя лучше 
10. Ок, всегда так буду делать

P.S. Спасиб, за ревью. =) Надеюсь, ничего не сломала своими правками
